{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9cb1fa23",
   "metadata": {},
   "outputs": [],
   "source": [
    "Question 1)\n",
    "The try statement in Python is used to execute a block of code and catch any exceptions that are raised. The try statement is followed by an except clause, which specifies what to do if an exception is raised. The except clause can be used to handle specific exceptions or all exceptions.\n",
    "\n",
    "For example, the following code will try to open a file and print its contents. If the file cannot be opened, the except clause will print an error message:\n",
    "\n",
    "try:\n",
    "with open(\"myfile.txt\", \"r\") as f:\n",
    "    print(f.read())\n",
    "except FileNotFoundError: \n",
    "    print(\"File not found\")\n",
    "The try statement can also be used with a finally clause. The finally clause is executed regardless of whether or not an exception is raised. The finally clause is often used to close files or release resources.\n",
    "\n",
    "For example, the following code will close the file myfile.txt even if an exception is raised: try:\n",
    "with open(\"myfile.txt\", \"r\") as f: \n",
    "    print(f.read())\n",
    "finally:\n",
    "    f.close()\n",
    "\n",
    "Here are some other things to keep in mind about the try statement:\n",
    "•\tThe try statement can be nested, meaning that you can have a try statement inside another try statement.\n",
    "•\tThe except clause can be used to handle multiple exceptions by specifying a list of exceptions.\n",
    "•\tThe else clause can be used to execute code if no exception is raised.\n",
    "•\tThe finally clause is always executed, regardless of whether or not an exception is raised.\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "77689e0c",
   "metadata": {},
   "outputs": [],
   "source": [
    "Question 2)\n",
    "\n",
    "The two most popular variations of the try statement in Python are:\n",
    "\"try-except\":\n",
    "The ‘try-except’ variation is used to catch and handle specific exceptions that may occur within the try block. It allows you to define custom actions for different types of exceptions. If an exception occurs in the try block, the corresponding except block is executed, and the program can gracefully handle the error without \"crashing.\n",
    "\n",
    "try: # Code that may raise an exception\n",
    "    result = 10 / 0 # This will raise a ZeroDivisionError\n",
    "except ZeroDivisionError:\n",
    "    print(\"Error: Division by zero occurred.\")\n",
    "\n",
    "try-except-else-\n",
    "The ‘try-except-else’ variation allows you to specify code that should be executed only if no exceptions occur in the try block. The else block is executed if no exceptions are raised during the execution of the try block. It is often used for the main code logic that should run only when no exceptions are encountered.#\n",
    "\n",
    "try:\n",
    "                           # Code that may or may not raise an exception\n",
    "    result = 10 / 2\n",
    "    except ZeroDivisionError:\n",
    "        print(\"Error: Division by zero occurred.\") \n",
    "else:\n",
    "    print(\"Result:\", result)\n",
    "\n",
    "In this example, the try block divides 10 by 2, which doesnt raise any exceptions. As a result, the else block is executed, printing \"Result: 5.\"\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "55326890",
   "metadata": {},
   "outputs": [],
   "source": [
    "Question 3)\n",
    "The ‘raise’ statement in Python is used to raise an exception. An exception is an event that occurs during the execution of a program that disrupts the normal flow of the program.\n",
    "When an exception is raised, the program stops executing the current code and jumps to the exception handler.\n",
    "The raise statement can also be used to re-raise an exception that has already been caught. This can be useful for propagating an exception to a higher level in the call stack.\n",
    "\n",
    "def divide_numbers(a, b): \n",
    "    if b == 0:\n",
    "        raise ValueError(\"Division by zero is not allowed.\")\n",
    "        return a / b\n",
    "\n",
    "try:\n",
    "    result = divide_numbers(10, 0) \n",
    "    except ValueError as ve:\n",
    "        print(f\"Error: {ve}\")\n",
    "\n",
    "In this example, the ‘divide_numbers’ function raises a ValueError with a custom error message when attempting to divide by zero. The raise statement is used to trigger this exception when the condition b == 0 is met. The try-except block then catches the exception and prints the error message\n",
    "\n",
    "Here are some other things to keep in mind about the raise statement:\n",
    "\n",
    "•\tThe raise statement can be used to raise any type of exception, including custom exceptions.\n",
    "•\tThe raise statement can be used to re-raise an exception that has already been caught.\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2bcc2834",
   "metadata": {},
   "outputs": [],
   "source": [
    "Question 4)\n",
    "The assert statement in Python is used to test a condition and raise an exception if the condition is not met. The assert statement is similar to the if statement, but it is used for\n",
    "debugging purposes. The assert statement is executed only when the ‘_debug_’ variable is set to ‘True’. If the ‘_debug_’ variable is set to ‘False’, the assert statement is skipped The basic syntax of the assert statement is as follows:\n",
    "assert expression, message expression: The condition that should be True. If this condition evaluates to False, an\n",
    "AssertionError is raised.\n",
    "message (optional): A custom error message that provides additional information about the assertion. This message will be displayed when the AssertionError is raised. It's useful for helping developers understand the reason for the failure.\n",
    "\n",
    "def divide_numbers(a, b):\n",
    "    assert b != 0, \"Division by zero is not allowed.\" \n",
    "    return a / b\n",
    "result = divide_numbers(10, 0)\n",
    "\n",
    "In this example, the assert statement checks that the value of b is not equal to zero before performing the division. If b is zero, the assert statement will raise an AssertionError with the custom message \"Division by zero is not allowed.\" The assert statement is a powerful tool for debugging Python code\n",
    "The assert statement is similar to the ‘if’ statement, but there are a few key differences:\n",
    "\n",
    " \n",
    "•\tThe assert statement is only executed when the __debug \n",
    "     variable is set to True.\n",
    "•\tThe assert statement raises an AssertionError exception if the condition is not met.\n",
    "•\tThe assert statement is often used for documentation purposes.\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bc6922f7",
   "metadata": {},
   "outputs": [],
   "source": [
    "Question 5)\n",
    "The ‘with/as’ statement in Python is used to simplify the management of resources. It allows you to ensure that resources are closed properly, even if an exception is raised.\n",
    "The with/as statement takes two arguments:\n",
    "•\tThe first argument is a resource, such as a file or a database connection.\n",
    "•\tThe second argument is a variable that will be bound to the resource.\n",
    "The with statement will execute the code block, and then it will close the resource. If an exception is raised, the resource will still be closed.\n",
    "The basic syntax of the with/as statement is as follows:\n",
    " \n",
    "with context_expression as target_variable:\n",
    "# Code block using the target_variable\n",
    "\n",
    "context_expression: An object that supports the context management protocol. It is typically created using a constructor or factory function.\n",
    "target_variable: The variable that will refer to the object created by the context_expression. It allows you to access and use the object inside the indented block.\n",
    "\n",
    "For example, the following code uses the with/as statement to open a file and read its contents:\n",
    "\n",
    "with open(\"myfile.txt\", \"r\") as f: \n",
    "    content = f.read()\n",
    "    print(content)\n",
    "\n",
    "The ‘with/as’ statement is similar to the ‘try/finally’ statement, but it is more concise and easier to use. The with/as statement is often used for managing files, database connections, and other resources.\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
